### ISSUE TITLE
Loading the trained model

### ISSUE THREAD

**Issue by EskildAndersen** [SHI-Labs/StyleNAT#14]
Where in the code are one supposed to load a pre-trained model for evaluation on let's say FFHQ-256?

**Comment by stevenwalton** [comment]
What issue are you running into? Did you check the [configs?](https://github.com/SHI-Labs/StyleNAT/tree/main/conf). The [inference config](https://github.com/SHI-Labs/StyleNAT/blob/main/conf/inference.yaml) has a minimal example of how to run inference, which includes loading a checkpoint). I also created [meta_conf](https://github.com/SHI-Labs/StyleNAT/blob/main/conf/meta_conf.yaml) which has all possible config options in an annotated form. Note that this won't work as its documentation, not an actual config. 

If you want to evaluate, you should set `type` to `evaluate`. [main file](https://github.com/SHI-Labs/StyleNAT/blob/main/main.py#L262-L275) will load the generator's checkpoint (if `restart.ckpt` is defined) and then decide which method to run. Training, inference, or evaluate. You can find the evaluation file [here](https://github.com/SHI-Labs/StyleNAT/blob/main/src/evaluate.py).

After reading the documentation (make sure you also read the README file), if you're still having problems let me know. Please provide the specific error and I'll do my best to help.
