### ISSUE TITLE
natten2d function requires kernel size

### ISSUE THREAD

**Issue by lzy00codeforfun** [SHI-Labs/StyleNAT#8]
Hi there,

Thanks for the great work! When I try to evaluate the FFHQ 256x256 generation, it seems the natten2d function requires kernel_size to be specified, both natten2dqkrpb and natten2dav. However, this is not specified in the code `models/stylenat.py`. I used this command to install the natten package, `pip3 install natten -f https://shi-labs.com/natten/wheels/cu118/torch2.0.0/index.html `. Is this because the code isn't compatible with this natten version? Do you have any idea of why this happens or what's the missing value here?

Thanks!

**Comment by alihassanijr** [comment]
Thank you for your interest and bringing this to our attention.

Yes, the issue is that NATTEN's function calls have a slightly different signature since v0.14.5, which is the release that added torch 2.0 support.
#9 should resolve the issue.

**Comment by stevenwalton** [comment]
Thanks @alihassanijr 

@lzy00codeforfun let us know if you have any additional issues. Please reopen if this did not resolve things. I also will note that you should probably see some speed improvements if using pytorch 2.0 but we have not tested StyleNAT under those settings. We are still using the same versioning as the paper. `torch==1.13.1`, `pytorch-cuda==1.7` `torchvision==0.14.1`. Natten versions (which @alihassanijr is the lead developer on) should, in general, not affect StyleNAT, but for what it is worth, my current environment has `natten==0.14.4` (still available through pip)
